services:
  pm-backend:
    image: php:8.3-fpm
    container_name: pm_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: php artisan serve --host=0.0.0.0 --port=8000
    environment:
      - DB_HOST=172.17.0.1
      - DB_DATABASE=password_manager

  pm-frontend:
    image: node:20-slim
    container_name: pm_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
